#!/usr/bin/env bash
set -e

function print_help() {
    echo "Usage: $0 <repo>"
}

while [ $# -gt 0 ]; do
  case "$1" in
  -h|--help)
    print_help
    exit 0
    ;;
  *) REPO_URL="$1"
    ;;
  esac
  shift
done

if [[ -z "$REPO_URL" ]]; then
    print_help
    exit 1
fi

ROOT=$(git config --get gh-get.root || true)
if [[ -z "$ROOT" ]]; then
    echo "Root Directory is not set! Please run 'git config --global gh-get.root <path>'."
    exit 1
fi

ROOT="${ROOT/#\~/$HOME}"

if [[ $REPO_URL =~ ^[a-zA-Z0-9_-]+$ ]]; then # repo
    REPO=$(gh api user --jq .login)/$REPO_URL
elif [[ $REPO_URL =~ ^[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$ ]]; then # owner/repo
    REPO=$REPO_URL
elif [[ $REPO_URL =~ ^github\.com/[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$ ]]; then # github.com/owner/repo
    REPO=$(cut -d/ -f2- <<< "$REPO_URL")
elif [[ $REPO_URL =~ ^https://github\.com/[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$ ]]; then # https://github.com/owner/repo
    REPO=$(cut -d/ -f4- <<< "$REPO_URL")
elif [[ $REPO_URL =~ ^https://github\.com/[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+\.git$ ]]; then # https://github.com/owner/repo.git
    REPO=$(cut -d/ -f4- <<< "$REPO_URL")
else
    echo "Invalid repo format: $REPO_URL" > /dev/stderr
    print_help
    exit 1
fi

DEST=$ROOT/github.com/$REPO
gh repo clone "$REPO" "$DEST"

# Ouput the path to the repo local dir.
printf "%s" "$DEST"
